[package]
name = "stringwars"
version = "0.1.0"
edition = "2018"

[dependencies]
rand = "0.8.5"
criterion = "0.5.1"
# stringzilla = { version = "3.3.0" }
stringzilla = { path = "../StringZilla/" }

# Feature-based dependencies for benchmarks
[features]
bench_find = ["memchr", "bstr", "aho-corasick", "regex"]
bench_hash = ["ahash", "xxhash-rust", "blake3", "gxhash"]
bench_sequence = ["arrow", "rayon"]
bench_similarity = ["rapidfuzz", "bio"]

[dependencies.memchr]
version = "2.7.1"
default-features = false
optional = true

[dependencies.bio]
version = "2.2.0"
default-features = false
optional = true

[dependencies.bstr]
version = "1.11.3"
default-features = false
optional = true

[dependencies.aho-corasick]
version = "1.1.3"
optional = true

[dependencies.regex]
version = "1.11.1"
optional = true

[dependencies.rapidfuzz]
version = "0.5.0"
optional = true

[dependencies.blake3]
version = "1.6.1"
optional = true

[dependencies.gxhash]
version = "3.4.1"
optional = true

[dependencies.ahash]
version = "0.8"
optional = true

[dependencies.xxhash-rust]
version = "0.8"
optional = true
features = ["xxh3", "const_xxh3"]

[dependencies.arrow]
version = "54.2.1"
optional = true

[dependencies.rayon]
version = "1.10.0"
optional = true

[[bench]]
name = "bench_find"
path = "bench_find.rs"
harness = false
required-features = ["bench_find"]

[[bench]]
name = "bench_similarity"
path = "bench_similarity.rs"
harness = false
required-features = ["bench_similarity"]

[[bench]]
name = "bench_hash"
path = "bench_hash.rs"
harness = false
required-features = ["bench_hash"]
