[package]
name = "stringwars"
version = "0.1.0"
edition = "2018"

[dependencies]
criterion = "0.7.0"
# stringzilla = { version = "3.3.0" }
stringzilla = { path = "../StringZilla/" }

# Feature-based dependencies for benchmarks
[features]
bench_find = [
    "memchr",       # Substring Search
    "bstr",         # Byteset Search
    "aho-corasick", # Byteset Search
    "regex",        # Byteset Search
]
bench_hash = [
    "ahash",       # Hashing
    "xxhash-rust", # One-Shot Hashing
    "twox-hash",   # One-Shot Hashing (same algo as xxHash)
    "gxhash",      # One-Shot Hashing
    "blake3",      # Cryptographic Hashing Baseline
]
bench_sequence = [
    "arrow", # Sorting
    "rayon", # Parallel Sorting
]
bench_similarity = [
    "rapidfuzz", # Levenshtein Distance (also `strsim`)
    "bio",       # Needleman-Wunsch Score
]
bench_memory = [
    # "opencv",    # Lookup Transform
    "rand",         # Randomize Buffer
    "zeroize",      # Obfuscate Buffer
    "getrandom",    # Randomize Buffer via OS
    "rand_chacha",  # Randomize Buffer
    "rand_xoshiro", # Randomize Buffer
]

# TODO: String properties:
# - `unicode-width`
# - `textwrap`
# - `unicode-segmentation`

[dependencies.memchr]
version = "2.7.1"
default-features = false
optional = true

[dependencies.bio]
version = "2.2.0"
default-features = false
optional = true

[dependencies.bstr]
version = "1.11.3"
default-features = false
optional = true

[dependencies.aho-corasick]
version = "1.1.3"
optional = true

[dependencies.regex]
version = "1.11.1"
optional = true

[dependencies.rapidfuzz]
version = "0.5.0"
optional = true

[dependencies.blake3]
version = "1.6.1"
optional = true

[dependencies.gxhash]
version = "3.4.1"
optional = true

[dependencies.ahash]
version = "0.8"
optional = true

[dependencies.xxhash-rust]
version = "0.8"
optional = true
features = ["xxh3", "const_xxh3"]

[dependencies.twox-hash]
version = "2.1.0"
optional = true

[dependencies.arrow]
version = "56.0.0"
optional = true

[dependencies.rayon]
version = "1.10.0"
optional = true

[dependencies.opencv]
version = "0.95.0"
optional = true

[dependencies.zeroize]
version = "1.8.1"
optional = true

[dependencies.getrandom]
version = "0.3.3"
optional = true

[dependencies.rand]
version = "0.9.2"
optional = true

[dependencies.rand_chacha]
version = "0.9.0"
optional = true

[dependencies.rand_xoshiro]
version = "0.7.0"
optional = true

[[bench]]
name = "bench_find"
path = "bench_find.rs"
harness = false
required-features = ["bench_find"]

[[bench]]
name = "bench_similarity"
path = "bench_similarity.rs"
harness = false
required-features = ["bench_similarity"]

[[bench]]
name = "bench_hash"
path = "bench_hash.rs"
harness = false
required-features = ["bench_hash"]

[[bench]]
name = "bench_sequence"
path = "bench_sequence.rs"
harness = false
required-features = ["bench_sequence"]

[[bench]]
name = "bench_memory"
path = "bench_memory.rs"
harness = false
required-features = ["bench_memory"]
